import os
import psycopg2
from dotenv import load_dotenv

load_dotenv()
DATABASE_URL = os.getenv('DATABASE_URL')

def init_trips_table():
    """Initialize trips table"""
    conn = psycopg2.connect(DATABASE_URL)
    try:
        with conn.cursor() as cur:
            cur.execute("""
                CREATE TABLE IF NOT EXISTS trips (
                    "trip_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    "user_id" text NOT NULL,
                    "title" text NOT NULL,
                    "description" text NOT NULL,
                    "start_date" date,
                    "end_date" date,
                    "create_date" timestamptz NOT NULL DEFAULT NOW()
                )
            """)
        conn.commit()
    finally:
        conn.close()


def init_experiences_table():
    """Initialize experiences table with last_updated timestamp"""
    conn = psycopg2.connect(DATABASE_URL)
    try:
        with conn.cursor() as cur:
            # Create "experiences" table
            cur.execute("""
                CREATE TABLE IF NOT EXISTS experiences (
                    "experience_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    "user_id" text NOT NULL,
                    "title" text NOT NULL,
                    "description" text NOT NULL,
                    "experience_date" date NOT NULL,
                    "create_date" timestamptz NOT NULL DEFAULT NOW(),
                    "last_updated" timestamptz,
                    "address" text NOT NULL,
                    "latitude" double precision NOT NULL,
                    "longitude" double precision NOT NULL
                )
            """)
        conn.commit()
    finally:
        conn.close()


def init_keywords_table():
    """Initialize keywords table"""
    conn = psycopg2.connect(DATABASE_URL)
    try:
        with conn.cursor() as cur:
            cur.execute("""
                CREATE TABLE IF NOT EXISTS keywords (
                    "keyword_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    "name" text UNIQUE NOT NULL
                )
            """)
        conn.commit()
    finally:
        conn.close()


def init_experience_keywords_table():
    """Initialize experience_keywords junction table"""
    conn = psycopg2.connect(DATABASE_URL)
    try:
        with conn.cursor() as cur:
            cur.execute("""
                CREATE TABLE IF NOT EXISTS experience_keywords (
                    "experience_id" integer NOT NULL,
                    "keyword_id" integer NOT NULL,
                    PRIMARY KEY (experience_id, keyword_id)
                )
            """)
        conn.commit()
    finally:
        conn.close()


def init_experience_ratings_table():
    """Initialize experience_ratings table"""
    conn = psycopg2.connect(DATABASE_URL)
    try:
        with conn.cursor() as cur:
            cur.execute("""
                CREATE TABLE IF NOT EXISTS experience_ratings (
                    "experience_id" integer NOT NULL,
                    "user_id" text NOT NULL,
                    "rating" smallint NOT NULL CHECK (rating BETWEEN 1 AND 5),
                    "created_at" timestamptz NOT NULL DEFAULT NOW(),
                    "updated_at" timestamptz NOT NULL DEFAULT NOW(),
                    PRIMARY KEY (experience_id, user_id)
                )
            """)

            cur.execute("""
                CREATE INDEX IF NOT EXISTS idx_experience_ratings_experience
                    ON experience_ratings (experience_id)
            """)
        conn.commit()
    finally:
        conn.close()


def init_trip_experiences_table():
    """Initialize trip_experiences junction table"""
    conn = psycopg2.connect(DATABASE_URL)
    try:
        with conn.cursor() as cur:
            cur.execute("""
                CREATE TABLE IF NOT EXISTS trip_experiences (
                    "trip_id" integer NOT NULL REFERENCES trips(trip_id) ON DELETE CASCADE,
                    "experience_id" integer NOT NULL REFERENCES experiences(experience_id) ON DELETE CASCADE,
                    "added_date" timestamptz NOT NULL DEFAULT NOW(),
                    PRIMARY KEY (trip_id, experience_id)
                )
            """)

            # Indexes for efficient queries
            cur.execute("""
                CREATE INDEX IF NOT EXISTS trip_experiences_trip_idx
                    ON trip_experiences ("trip_id")
            """)
            cur.execute("""
                CREATE INDEX IF NOT EXISTS trip_experiences_experience_idx
                    ON trip_experiences ("experience_id")
            """)
        conn.commit()
    finally:
        conn.close()


def init_experience_photos_table():
    """Initialize experience_photos table"""
    conn = psycopg2.connect(DATABASE_URL)
    try:
        with conn.cursor() as cur:
            cur.execute("""
                        CREATE TABLE IF NOT EXISTS experience_photos (
                    photo_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    experience_id integer NOT NULL REFERENCES experiences(experience_id) ON DELETE CASCADE,
                    photo_url text NOT NULL,
                    caption text DEFAULT '',
                    upload_date timestamptz NOT NULL DEFAULT NOW()
                            )
                        """)

            cur.execute("""
                        CREATE INDEX IF NOT EXISTS idx_experience_photos
                            ON experience_photos(experience_id)
                        """)
        conn.commit()
    finally:
        conn.close()



def init_all_tables():
    """Initialize all tables in the correct order"""
    # Base tables
    init_trips_table()
    init_experiences_table()
    init_keywords_table()

    # Junction tables
    init_experience_keywords_table()
    init_experience_ratings_table()
    init_experience_photos_table()
    init_trip_experiences_table()


# Initialize in order
if __name__ == "__main__":
    init_all_tables()
